apiVersion: batch/v1
kind: Job
metadata:
  name: descheduler-job
  namespace: kube-system
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
spec:
  template:
    spec:
      containers:
      - name: descheduler
        image: gcr.io/stae-product/descheduler:v0.8.0-37-g0866e248
        volumeMounts:
        - mountPath: /policy-dir
          name: policy-volume
        command:
          - /bin/descheduler
          - --policy-config-file
          - /policy-dir/policy.yaml
      restartPolicy: "Never"
      serviceAccountName: descheduler-sa
      volumes:
      - name: policy-volume
        configMap:
          name: descheduler-policy-configmap
